name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU for multi-architecture builds
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx for multi-architecture builds
      uses: docker/setup-buildx-action@v3
      with:
          use: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        subFolder: .github
        imageName: ghcr.io/webhdx/picoboot
        cacheFrom: ghcr.io/webhdx/picoboot
        push: always
        platform: linux/amd64,linux/arm64
